#reference here: https://www.appveyor.com/docs/appveyor-yml/

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: '1.0.{build}'


#---------------------------------#
#    environment configuration    #
#---------------------------------#
environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration:
- Debug
#- Release disable relese for right now till we get valid docker files

build:
  parallel: true                  # enable MSBuild parallel builds
  verbosity: minimal              # MSBuild verbosity level
  project: CVPZ.sln               # path to Visual Studio solution or project

# scripts to run before build
before_build:
  nuget restore


#---------------------------------#
#         notifications           #
#---------------------------------#
notifications:
  - provider: Slack
    auth_token:
      secure: WcnxbrAG2PIcKRS2fYEvq0QnjRrYZO2n/sz1MnHPHMwqjY9jZwrUkDp/hm/uY1hX
    channel: cvpz
