version: '2'

services:

  ci-build-angular:
    image: alexsuch/angular-cli
    volumes:
      - ./src/WebUI:/src
    working_dir: /src
    command: /bin/sh -c "npm install --silent && ng build"

  ci-build-netcore:
    image: microsoft/aspnetcore-build:1.0-1.1
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./CVPZ.sln && dotnet publish ./CVPZ.sln -c Release -o ./obj/Docker/publish"
